recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, search, add_recipe, about

app_name = "recipes"

urlpatterns = [
    path("", home, name="home"),
    path("collection", RecipeListView.as_view(), name="list"),
    path("collection/<pk>", RecipeDetailView.as_view(), name="detail"),
    path("search", search, name="search"),
    path("add_recipe", add_recipe, name="add_recipe"),
    path("about", about, name="about"),
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse
from cloudinary.models import CloudinaryField

# Create your models here.
class Recipe(models.Model):
    # Class attributes
    name = models.CharField(max_length=50)
    ingredients = models.CharField(
        max_length=255,
        help_text='Enter ingredients, separated by a comma.'
    )
    cooking_time = models.IntegerField(help_text='Enter cooking time (minutes).')
    pic = CloudinaryField('image', default="no_picture.jpg")


    # Determines recipe difficulty
    @property
    def difficulty(self):
        ingredients = self.ingredients.split(", ")

        if self.cooking_time < 10 and len(ingredients) < 4:
            return 'Easy'
        elif self.cooking_time < 10 and len(ingredients) >= 4:
            return 'Medium'
        elif self.cooking_time >= 10 and len(ingredients) < 4:
            return 'Intermediate'
        elif self.cooking_time >= 10 and len(ingredients) >= 4:
            return 'Hard'
        return 'Unknown'

    # String representation
    def __str__(self):
        return str(self.name)
    
    # Creates the primary key of the recipe objects to become clickable
    def get_absolute_url(self):
        return reverse ('recipes:detail', kwargs={'pk': self.pk})
    
    # Split the ingredients field by commas and return as a list.
    def return_ingredients_as_list(self):
        return self.ingredients.split(",") # Split the ingredients field by commas and return as a list.

recipes/forms.py
from django import forms
from .models import Recipe

SEARCH_CHOICES = [
    ("name", "Recipe Name"),
    ("ingredients", "Ingredients"),
    ("difficulty", "Difficulty"),
]

# CBV "RecipesSearchForm"
class RecipesSearchForm(forms.Form):
    search_by = forms.ChoiceField(choices=SEARCH_CHOICES, required=True, label="Search by")
    search_term = forms.CharField(max_length=100, required=False, label="Search term")
    ingredients = forms.CharField(max_length=100, required=False, label="Ingredients")
    difficulty = forms.ChoiceField(
        choices=[
            ("Easy", "Easy"),
            ("Medium", "Medium"),
            ("Intermediate", "Intermediate"),
            ("Hard", "Hard"),
        ],
        required=False,
        label="Difficulty"
    )

# CBV "AddRecipeForm"
class AddRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "name",
            "ingredients",
            "cooking_time",
            "pic"
        ]

recipes/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
import pandas as pd
from .models import Recipe
from .forms import RecipesSearchForm, AddRecipeForm
from .utils import get_chart


# Create your views here.
# FBV "home"
def home(request):
    return render(request, "recipes/recipes_home.html")

# FBV "about"
def about(request):
    return render(request, "recipes/about.html")

# CBV "RecipeList", protected
class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe

    template_name = "recipes/collection.html"

# CBV "RecipeDetail", protected
class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe

    template_name = "recipes/detail.html"

# FBV "search", protected
@login_required
def search(request):
    # adds an instance of RecipesSearchForm
    form = RecipesSearchForm(request.POST or None)

    # Initializes dataframe to None
    recipes_df = None

    bar_chart = None
    pie_chart = None
    line_chart = None

    if request.method == "POST" and form.is_valid():
        # Retrieves the search criteria from the form
        search_by = form.cleaned_data.get("search_by")
        search_term = form.cleaned_data.get("search_term")
        ingredients = form.cleaned_data.get("ingredients")
        difficulty = form.cleaned_data.get("difficulty")

        # Filters the queryset based on the form input
        qs = Recipe.objects.all()

        if search_by == "name" and search_term:
            qs = qs.filter(name__icontains=search_term)
        elif search_by == "ingredients" and ingredients is not None:
            qs = qs.filter(ingredients=ingredients)
        elif search_by == "difficulty" and difficulty:
            qs = [recipe for recipe in qs if recipe.difficulty == difficulty]

        # Checks if the queryset is not empty
        if qs:
            # Converts list to pandas dataframe, else converts queryset to pandas DataFrame
            if isinstance(qs, list):
                recipes_df = pd.DataFrame([recipe.__dict__ for recipe in qs])
            else:
                recipes_df = pd.DataFrame(qs.values())

            recipes_df.index += 1

            # Retrieves each Recipe object using its id, then calls get_absolute_url() on it to generate the link
            def format_recipe_name_table(row):
                recipe = Recipe.objects.get(id=row["id"])
                return f"<a href='{recipe.get_absolute_url()}'>{row['name']}</a>"
            
            def format_recipe_name_chart(row):
                return row["name"]

            recipes_df["name_table"] = recipes_df.apply(format_recipe_name_table, axis=1)
            recipes_df["name_chart"] = recipes_df.apply(format_recipe_name_chart, axis=1)

            # Calculates difficulty and number of ingredients for each recipe
            recipes_df["difficulty"] = [recipe.difficulty for recipe in qs]
            recipes_df["number_of_ingredients"] = recipes_df["ingredients"].apply(lambda x: len(x.split(", ")))

            # Generate charts
            bar_chart = get_chart("#1", recipes_df, labels=recipes_df["name_chart"].values)
            pie_chart = get_chart("#2", recipes_df, labels=recipes_df["difficulty"].values)
            line_chart = get_chart("#3", recipes_df, labels=recipes_df["name_chart"].values)

            recipes_df = recipes_df[["name_table", "cooking_time", "difficulty"]]
            recipes_df = recipes_df.rename(columns={"name_table": "Name"})
            recipes_df = recipes_df.rename(columns={"cooking_time": "Cooking Time (in minutes)"})
            recipes_df.columns = recipes_df.columns.str.capitalize()

            # Convert DataFrame to HTML for display
            recipes_df = recipes_df.to_html(escape=False)


    # Prepares data to send from view to template
    context = {
        "form": form,
        "recipes_df": recipes_df,
        "bar_chart": bar_chart,
        "pie_chart": pie_chart,
        "line_chart": line_chart,
    }

    # Loads page using "context" information
    return render(request, "recipes/search.html", context)

# FBV "add_recipe"
@login_required
def add_recipe(request):

    if request.method == "POST":
        # Creates an instance of AddRecipeForm with the submitted data and files
        add_recipe_form = AddRecipeForm(request.POST, request.FILES)

        # Validates form data
        if add_recipe_form.is_valid():
            # Saves form data to database
            add_recipe_form.save()

            # Adds a success message to display to user
            messages.success(request, "Recipe added successfully.")

            # Redirects user to "add_recipe" page
            return redirect("recipes:list")
    else:
        # Creates an empty form instance if request method is not POST
        add_recipe_form = AddRecipeForm()

    # Prepares data to send from view to template
    context = {
        "add_recipe_form": add_recipe_form
    }

    # Loads page using "context" information
    return render(request, "recipes/add_recipe.html", context)

recipes/templates/recipes/about.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Recipes - About{% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/about.css' %}">
    </head>

    <body>
        {% block content %}
            <h1>About Me</h1>

            <div class="about-container">
                <h2 class="contact-header">Contact Info</h2>
                
                <div>Email: <a href="mailto:ccashley12@gmail.com">ccashley12@gmail.com</a></div>

                <div>Portfolio: <a href="https://ccashley12.github.io/portfolio-site/index.html" target="_blank">Portfolio</a></div>

                <div>LinkedIn: <a href="https://www.linkedin.com/in/christopher-ashley-7a492b191/" target="_blank">LinkedIn</a></div>

                <div>GitHub: <a href="https://github.com/ccashley12" target="_blank">GitHub</a></div>
            </div>
        {% endblock %}
    </body>
</html>

recipes/templates/recipes/add_recipe.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Recipes - Add Your Recipe{% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/add_recipe.css' %}">
    </head>

    <body>
        {% block content %}
            <h1>Add Recipe</h1>
        
            {% if messages %}
                {% for message in messages %}
                    <script>alert("{{ message }}");</script>
                {% endfor %}
            {% endif %}
        
            <div class="add-form">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="id_name">Recipe Name:</label>

                        <input type="text" name="name" id="id_name" required>
                    </div>

                    <div class="form-group">
                        <label for="id_ingredients">Ingredients:</label>
                        
                        <textarea name="ingredients" id="id_ingredients" required></textarea>
                    </div>

                    <div class="form-group">
                        <label for="id_cooking_time">Cooking Time (in minutes):</label>
                        
                        <input type="number" name="cooking_time" id="id_cooking_time" required>
                    </div>

                    <div class="form-group">
                        <label for="id_picture">Picture:</label>
                        
                        <input type="file" name="pic" id="id_picture">
                    </div>

                    <button type="submit">Add Recipe</button>
                </form>      
            </div>
        {% endblock %}
    </body>
</html>

recipes/templates/recipes/collection.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Recipes - Collection{% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/collection.css' %}">
    </head>

    <body>
        {% block content %}
            <h1>Recipes - Collection</h1>

            <!-- Table displaying recipes and their images -->
            <table border="1" cellpadding="5" cellspacing="5">
                <tr>
                    <td>Recipe Name</td>
                    <td>Image</td>
                </tr>

                {% for object in object_list %}
                <tr>
                    <td>
                        <a class="recipe-name" href="{{object.get_absolute_url}}">{{object.name}}</a>
                    </td>
                    
                    <td>
                        <a href="{{object.get_absolute_url}}"><img src="{{object.pic.url}}"></a>
                    </td>
                </tr>
                
                <br>
                {% endfor %}   
            </table>
        {% endblock %}
    </body>
</html>

recipes/templates/recipes/detail.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Recipes - {{object.name}}{% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/detail.css' %}">
    </head>

    <body>
        {% block content %}
            <h1 class="detail-header">Details: {{object.name}}</h1>
            
            <div class="details-container">
                <b>Ingredients: </b> {{object.ingredients}}

                <br>

                <b>Cooking Time (in minutes): </b> {{object.cooking_time}}

                <br>

                <b>Difficulty: </b> {{object.difficulty}}

                <br>

                <img src="{{object.pic.url}}" alt="{{object.name}}">
            </div>
        {% endblock %}
    </body>
</html>

recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Recipes - Home</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
        <link href="{% static 'recipes/css/home.css' %}" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            <h1>Recipes</h1>

            <p>Search for Recipes and Add Your Own Recipe</p>

            <br>
            <a href="{% url 'login' %}">Login</a>
        </div>
    </body>
</html>

recipes/templates/recipes/search.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Recipes - Search{% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/search.css' %}">
    </head>

    <body>
        {% block content %}
            <h1 class="search-header">Search for recipes</h1>

            <!-- Search form -->
            <div class="search-form">
                <form method="POST" novalidate>
                    {% csrf_token %}

                    <!-- Dropdown to select the search criterion -->
                    {{ form.search_by.label_tag }} {{ form.search_by }}

                    <!-- Div for inputting the recipe name, hidden by default -->
                    <div id="search_term_div" style="display: none;">
                        {{ form.search_term.label_tag }} {{ form.search_term }}
                    </div>

                    <!-- Div for inputting the ingredients, hidden by default -->
                    <div id="ingredients_div" style="display: none;">
                        {{ form.ingredients.label_tag }} {{ form.ingredients }}
                    </div>

                    <!-- Div for selecting the difficulty, hidden by default -->
                    <div id="difficulty_div" style="display: none;">
                        {{ form.difficulty.label_tag }} {{ form.difficulty }}
                    </div>

                    <!-- Submit Button -->
                    <button type="submit">Search</button>
                </form>
            </div>

            <br>

            <!-- Checks if there is any data in recipes_df -->
            {% if recipes_df %}
                <h2 class="results-header">Search Results</h2>
                {{recipes_df | safe}}

                <br>

                <!-- Bar Chart -->
                <h3>Bar Chart: Cooking Time per Recipe</h3>
                <img class="chart-image" src="data:image/png;base64,{{ bar_chart }}" alt="Bar Chart">

                <!-- Pie Chart -->
                <h3>Pie Chart: Percentage of Recipe Difficulties</h3>
                <img class="chart-image" src="data:image/png;base64,{{ pie_chart }}" alt="Pie Chart">

                <!-- Line Chart -->
                <h3>Line Chart: Number of Ingredients per Recipe</h3>
                <img class="chart-image" src="data:image/png;base64,{{ line_chart }}" alt="Line Chart">

            {% else %}
                <h3>Nothing to see here...</h3>
            {% endif %}

            <script>
                document.addEventListener("DOMContentLoaded", function () {
                    // Gets references to the form elements
                    const searchByField = document.getElementById("id_search_by");
                    const searchTermDiv = document.getElementById("search_term_div");
                    const ingredientsDiv = document.getElementById("ingredients_div");
                    const difficultyDiv = document.getElementById("difficulty_div");
            
                    // Function to update the visibility of search input fields based on the selected criterion
                    function updateSearchFields() {
                        // Gets the selected value from the dropdown
                        const searchByValue = searchByField.value;

                        // Hide all search input fields by default
                        searchTermDiv.style.display = "none";
                        ingredientsDiv.style.display = "none";
                        difficultyDiv.style.display = "none";
            
                        // Show the appropriate input field based on the selected search criterion
                        if (searchByValue === "name") {
                            searchTermDiv.style.display = "block";
                        } else if (searchByValue === "ingredients") {
                            ingredientsDiv.style.display = "block";
                        } else if (searchByValue === "difficulty") {
                            difficultyDiv.style.display = "block";
                        }
                    }
                    
                    // Add event listener to the dropdown to update search fields when the selected value changes
                    searchByField.addEventListener("change", updateSearchFields);

                    // Initial call to set the correct fields based on default or current selected value
                    updateSearchFields();
                });
            </script>
        {% endblock %}
    </body>
</html>