recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, search, add_recipe, about

app_name = "recipes"

urlpatterns = [
    path("", home, name="home"),
    path("collection", RecipeListView.as_view(), name="list"),
    path("collection/<pk>", RecipeDetailView.as_view(), name="detail"),
    path("search", search, name="search"),
    path("add_recipe", add_recipe, name="add_recipe"),
    path("about", about, name="about"),
]

templates/navigation/navigation.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Navbar</title>
        <link href="https://fonts.googleapis.com/css2?family=Playwrite+DE+Grund&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>

    <body class="body">
        <header>
            <nav class="navbar">
                <div class="container">
                    <a href="{% url 'recipes:list' %}" class="navbar-brand">Recipes</a>
                    
                    <ul class="navbar-nav">
                        <li class="nav-item"><a href="{% url 'recipes:about' %}" class="nav-link">About</a></li>
                        
                        <li class="nav-item"><a href="{% url 'recipes:list' %}" class="nav-link">Collection</a></li>
                        
                        <li class="nav-item"><a href="{% url 'recipes:search' %}" class="nav-link">Search</a></li>

                        <li class="nav-item"><a href="{% url 'recipes:add_recipe' %}" class="nav-link">Add Recipe</a></li>
                        
                        <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
                    </ul>
                </div>
            </nav>
        </header>
    </body>
</html>